# Generated by Django 5.1.7 on 2025-07-16 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time_create']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_time_cr_62f8ed_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['time_create'], name='api_message_time_cr_694512_idx'),
        ),
    ]
